import type { SensorDefinition } from '../sensors/types.js';
import { createVirtualTotals } from './common.js';

/**
 * Sensor definitions for Deye SUN-6K/8K/10K/12K (3-phase Low Voltage).
 * Based on Modbus register map from Deye documentation and sunsynk project.
 */
export const DEYE_SUN_3PHASE_LV: SensorDefinition[] = [
  // === Virtual totals (unified across all models) ===
  ...createVirtualTotals({
    solar: { sumOf: [674, 678] },
    grid: { address: 619 },           // external_ct_total_power
    load: { address: 653 },
    inverter: { address: 636 },
    battery: { address: 590 },
  }),

  // === PV / DC input ===
  {
    id: 'pv1_voltage',
    name: 'PV1 Voltage',
    address: 672,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'pv1_current',
    name: 'PV1 Current',
    address: 673,
    size: 1,
    factor: 0.1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'pv1_power',
    name: 'PV1 Power',
    address: 674,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'pv2_voltage',
    name: 'PV2 Voltage',
    address: 676,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'pv2_current',
    name: 'PV2 Current',
    address: 677,
    size: 1,
    factor: 0.1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'pv2_power',
    name: 'PV2 Power',
    address: 678,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  {
    id: 'pv_total_power',
    name: 'PV Total Power',
    address: 0,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
    sumOf: [674, 678],
  },

  // === Grid / AC output ===
  {
    id: 'grid_voltage_l1',
    name: 'Grid Voltage L1',
    address: 598,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'grid_voltage_l2',
    name: 'Grid Voltage L2',
    address: 599,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'grid_voltage_l3',
    name: 'Grid Voltage L3',
    address: 600,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'internal_ct_l1_power',
    name: 'Internal CT L1 Power',
    address: 604,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'internal_ct_l2_power',
    name: 'Internal CT L2 Power',
    address: 605,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'internal_ct_l3_power',
    name: 'Internal CT L3 Power',
    address: 606,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'grid_frequency',
    name: 'Grid Frequency',
    address: 609,
    size: 1,
    factor: 0.01,
    unit: 'Hz',
    signed: false,
    deviceClass: 'frequency',
    stateClass: 'measurement',
  },

  // === External CT (grid power) ===
  {
    id: 'external_ct_l1_power',
    name: 'External CT L1 Power',
    address: 616,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_l2_power',
    name: 'External CT L2 Power',
    address: 617,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_l3_power',
    name: 'External CT L3 Power',
    address: 618,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_total_power',
    name: 'External CT Total Power',
    address: 619,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  // === Inverter output ===
  {
    id: 'inverter_l1_power',
    name: 'Inverter L1 Power',
    address: 633,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_l2_power',
    name: 'Inverter L2 Power',
    address: 634,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_l3_power',
    name: 'Inverter L3 Power',
    address: 635,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  {
    id: 'inverter_total_power',
    name: 'Inverter Total Power',
    address: 636,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  // === Load ===
  {
    id: 'load_l1_power',
    name: 'Load L1 Power',
    address: 650,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'load_l2_power',
    name: 'Load L2 Power',
    address: 651,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'load_l3_power',
    name: 'Load L3 Power',
    address: 652,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'load_total_power',
    name: 'Load Total Power',
    address: 653,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  // === Battery ===
  {
    id: 'battery_voltage',
    name: 'Battery Voltage',
    address: 587,
    size: 1,
    factor: 0.01,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'battery_current',
    name: 'Battery Current',
    address: 588,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'battery_power',
    name: 'Battery Power',
    address: 590,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'battery_soc',
    name: 'Battery SOC',
    address: 588,
    size: 1,
    factor: 1,
    unit: '%',
    signed: false,
    deviceClass: 'battery',
    stateClass: 'measurement',
  },
  {
    id: 'battery_temperature',
    name: 'Battery Temperature',
    address: 586,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },

  // === Temperatures ===
  {
    id: 'dc_temperature',
    name: 'DC Temperature',
    address: 541,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },
  {
    id: 'ac_temperature',
    name: 'AC Temperature',
    address: 542,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },

  // === Energy totals ===
  {
    id: 'day_grid_import',
    name: 'Day Grid Import',
    address: 526,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_grid_export',
    name: 'Day Grid Export',
    address: 527,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_pv_energy',
    name: 'Day PV Energy',
    address: 529,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_load_energy',
    name: 'Day Load Energy',
    address: 530,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_battery_charge',
    name: 'Day Battery Charge',
    address: 514,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_battery_discharge',
    name: 'Day Battery Discharge',
    address: 515,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_pv_energy',
    name: 'Total PV Energy',
    address: 534,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_load_energy',
    name: 'Total Load Energy',
    address: 527,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },

  // === Status ===
  {
    id: 'running_status',
    name: 'Running Status',
    address: 500,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Standby',
      1: 'Self Check',
      2: 'Normal',
      3: 'Alarm',
      4: 'Fault',
    },
  },
];
