import type { SensorDefinition } from '../sensors/types.js';
import { createVirtualTotals } from './common.js';

/**
 * Sensor definitions for Deye single-phase hybrid inverters (2 MPPT).
 * Models: SUN-5K/6K-SG03LP1-EU, SUN-3.6K÷6K-SG04LP1-EU.
 *
 * Register map is completely different from 3-phase models (range 0–319).
 * Based on sunsynk single_phase.py and deye-inverter-mqtt deye_hybrid.
 */
export const DEYE_HYBRID_1P: SensorDefinition[] = [
  // === Virtual totals (unified across all models) ===
  ...createVirtualTotals({
    solar: { address: 184 },
    grid: { address: 169 },
    load: { address: 178, signed: true },
    inverter: { address: 175 },
    battery: { address: 190 },
    generator: { address: 166 },        // aux_power
  }),

  // =========================================================================
  // PV / DC input (2 MPPT)
  // =========================================================================
  {
    id: 'pv1_power',
    name: 'PV1 Power',
    address: 186,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'pv2_power',
    name: 'PV2 Power',
    address: 187,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'pv1_voltage',
    name: 'PV1 Voltage',
    address: 109,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'pv1_current',
    name: 'PV1 Current',
    address: 110,
    size: 1,
    factor: 0.1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'pv2_voltage',
    name: 'PV2 Voltage',
    address: 111,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'pv2_current',
    name: 'PV2 Current',
    address: 112,
    size: 1,
    factor: 0.1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },

  {
    id: 'pv_total_power',
    name: 'PV Total Power',
    address: 184,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Grid
  // =========================================================================
  {
    id: 'grid_voltage',
    name: 'Grid Voltage',
    address: 150,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'grid_frequency',
    name: 'Grid Frequency',
    address: 79,
    size: 1,
    factor: 0.01,
    unit: 'Hz',
    signed: false,
    deviceClass: 'frequency',
    stateClass: 'measurement',
  },
  {
    id: 'grid_current',
    name: 'Grid Current',
    address: 160,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'grid_l1_power',
    name: 'Grid L1 Power',
    address: 167,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'grid_total_power',
    name: 'Grid Total Power',
    address: 169,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_l1_power',
    name: 'External CT L1 Power',
    address: 170,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_total_power',
    name: 'External CT Total Power',
    address: 172,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Inverter output
  // =========================================================================
  {
    id: 'inverter_voltage',
    name: 'Inverter Voltage',
    address: 154,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_current',
    name: 'Inverter Current',
    address: 164,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_l1_power',
    name: 'Inverter L1 Power',
    address: 173,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_total_power',
    name: 'Inverter Total Power',
    address: 175,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_frequency',
    name: 'Inverter Frequency',
    address: 193,
    size: 1,
    factor: 0.01,
    unit: 'Hz',
    signed: false,
    deviceClass: 'frequency',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Load
  // =========================================================================
  {
    id: 'load_voltage',
    name: 'Load Voltage',
    address: 157,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'load_l1_power',
    name: 'Load L1 Power',
    address: 176,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'load_total_power',
    name: 'Load Total Power',
    address: 178,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'load_frequency',
    name: 'Load Frequency',
    address: 192,
    size: 1,
    factor: 0.01,
    unit: 'Hz',
    signed: false,
    deviceClass: 'frequency',
    stateClass: 'measurement',
  },

  // =========================================================================
  // AUX / Generator
  // =========================================================================
  {
    id: 'aux_power',
    name: 'AUX Power',
    address: 166,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'aux_voltage',
    name: 'AUX Voltage',
    address: 181,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Battery
  // =========================================================================
  {
    id: 'battery_temperature',
    name: 'Battery Temperature',
    address: 182,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },
  {
    id: 'battery_voltage',
    name: 'Battery Voltage',
    address: 183,
    size: 1,
    factor: 0.01,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'battery_soc',
    name: 'Battery SOC',
    address: 184,
    size: 1,
    factor: 1,
    unit: '%',
    signed: false,
    deviceClass: 'battery',
    stateClass: 'measurement',
  },
  {
    id: 'battery_status',
    name: 'Battery Status',
    address: 189,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Charging',
      1: 'Standby',
      2: 'Discharging',
    },
  },
  {
    id: 'battery_power',
    name: 'Battery Power',
    address: 190,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'battery_current',
    name: 'Battery Current',
    address: 191,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },

  // =========================================================================
  // BMS
  // =========================================================================
  {
    id: 'bms_charging_voltage',
    name: 'BMS Charging Voltage',
    address: 312,
    size: 1,
    factor: 0.01,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'bms_discharging_voltage',
    name: 'BMS Discharging Voltage',
    address: 313,
    size: 1,
    factor: 0.01,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'bms_charging_current_limit',
    name: 'BMS Charging Current Limit',
    address: 314,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'bms_discharging_current_limit',
    name: 'BMS Discharging Current Limit',
    address: 315,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'bms_soc',
    name: 'BMS SOC',
    address: 316,
    size: 1,
    factor: 1,
    unit: '%',
    signed: false,
    deviceClass: 'battery',
    stateClass: 'measurement',
  },
  {
    id: 'bms_voltage',
    name: 'BMS Voltage',
    address: 317,
    size: 1,
    factor: 0.01,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'bms_current',
    name: 'BMS Current',
    address: 318,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'bms_temperature',
    name: 'BMS Temperature',
    address: 319,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Temperatures
  // =========================================================================
  {
    id: 'dc_temperature',
    name: 'DC Temperature',
    address: 90,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },
  {
    id: 'ac_temperature',
    name: 'AC Temperature',
    address: 91,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },
  {
    id: 'environment_temperature',
    name: 'Environment Temperature',
    address: 95,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Energy totals (daily)
  // =========================================================================
  {
    id: 'day_pv_energy',
    name: 'Day PV Energy',
    address: 108,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_battery_charge',
    name: 'Day Battery Charge',
    address: 70,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_battery_discharge',
    name: 'Day Battery Discharge',
    address: 71,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_grid_import',
    name: 'Day Grid Import',
    address: 76,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_grid_export',
    name: 'Day Grid Export',
    address: 77,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_load_energy',
    name: 'Day Load Energy',
    address: 84,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },

  // =========================================================================
  // Energy totals (lifetime, 32-bit)
  // =========================================================================
  {
    id: 'total_pv_energy',
    name: 'Total PV Energy',
    address: 96,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_battery_charge',
    name: 'Total Battery Charge',
    address: 72,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_battery_discharge',
    name: 'Total Battery Discharge',
    address: 74,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_grid_export',
    name: 'Total Grid Export',
    address: 81,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_grid_import',
    name: 'Total Grid Import',
    address: 78,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_load_energy',
    name: 'Total Load Energy',
    address: 85,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },

  // =========================================================================
  // Hybrid settings (read-only monitoring)
  // =========================================================================
  {
    id: 'work_mode',
    name: 'Work Mode',
    address: 244,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Export First',
      1: 'Zero Export to Load',
      2: 'Zero Export to CT',
    },
  },
  {
    id: 'battery_max_charge_current',
    name: 'Battery Max Charge Current',
    address: 210,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'battery_max_discharge_current',
    name: 'Battery Max Discharge Current',
    address: 211,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'battery_shutdown_soc',
    name: 'Battery Shutdown SOC',
    address: 217,
    size: 1,
    factor: 1,
    unit: '%',
    signed: false,
    stateClass: 'measurement',
  },
  {
    id: 'battery_low_soc',
    name: 'Battery Low SOC',
    address: 219,
    size: 1,
    factor: 1,
    unit: '%',
    signed: false,
    stateClass: 'measurement',
  },

  // =========================================================================
  // Status
  // =========================================================================
  {
    id: 'running_status',
    name: 'Running Status',
    address: 59,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Standby',
      1: 'Self Check',
      2: 'Normal',
      3: 'Alarm',
      4: 'Fault',
    },
  },
  {
    id: 'grid_connected',
    name: 'Grid Connected',
    address: 194,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Off-Grid',
      1: 'On-Grid',
    },
  },
];
