import type { SensorDefinition } from '../sensors/types.js';
import { createVirtualTotals } from './common.js';

/**
 * Sensor definitions for Deye SUN-*K-SG05LP3-EU (3-phase Hybrid LV).
 * Models: SUN-5K, SUN-6K, SUN-8K, SUN-10K, SUN-12K, SUN-20K (SG05LP3-EU-SM2).
 *
 * Register map based on Deye Modbus protocol V1.05 and ha-solarman deye_p3.yaml.
 * Same register layout as SG04LP3 series.
 *
 * Key differences from deye-sun-3phase-lv:
 * - PV registers: power at 672-675, voltage/current at 676-683
 * - Additional hybrid registers: work mode, BMS, time-of-use, generator
 * - 32-bit high-word registers for power values > 32767W
 * - Battery SOC at register 588, battery current at 591
 */
export const DEYE_SG05LP3: SensorDefinition[] = [
  // === Virtual totals (unified across all models) ===
  ...createVirtualTotals({
    solar: { address: 675 },
    grid: { address: 625 },            // grid_total_power
    load: { address: 653 },
    inverter: { address: 636 },
    battery: { address: 590 },
  }),

  // =========================================================================
  // PV / DC input (2 MPPT)
  // =========================================================================
  {
    id: 'pv1_power',
    name: 'PV1 Power',
    address: 672,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'pv2_power',
    name: 'PV2 Power',
    address: 673,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'pv1_voltage',
    name: 'PV1 Voltage',
    address: 676,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'pv1_current',
    name: 'PV1 Current',
    address: 677,
    size: 1,
    factor: 0.1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'pv2_voltage',
    name: 'PV2 Voltage',
    address: 678,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'pv2_current',
    name: 'PV2 Current',
    address: 679,
    size: 1,
    factor: 0.1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },

  {
    id: 'pv_total_power',
    name: 'PV Total Power',
    address: 675,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Grid / AC
  // =========================================================================
  {
    id: 'grid_voltage_l1',
    name: 'Grid Voltage L1',
    address: 598,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'grid_voltage_l2',
    name: 'Grid Voltage L2',
    address: 599,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'grid_voltage_l3',
    name: 'Grid Voltage L3',
    address: 600,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'grid_frequency',
    name: 'Grid Frequency',
    address: 609,
    size: 1,
    factor: 0.01,
    unit: 'Hz',
    signed: false,
    deviceClass: 'frequency',
    stateClass: 'measurement',
  },

  // --- Internal CT ---
  {
    id: 'internal_ct_l1_power',
    name: 'Internal CT L1 Power',
    address: 604,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'internal_ct_l2_power',
    name: 'Internal CT L2 Power',
    address: 605,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'internal_ct_l3_power',
    name: 'Internal CT L3 Power',
    address: 606,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'internal_ct_total_power',
    name: 'Internal CT Total Power',
    address: 607,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'internal_ct_l1_current',
    name: 'Internal CT L1 Current',
    address: 610,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'internal_ct_l2_current',
    name: 'Internal CT L2 Current',
    address: 611,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'internal_ct_l3_current',
    name: 'Internal CT L3 Current',
    address: 612,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },

  // --- External CT (grid meter) ---
  {
    id: 'external_ct_l1_power',
    name: 'External CT L1 Power',
    address: 616,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_l2_power',
    name: 'External CT L2 Power',
    address: 617,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_l3_power',
    name: 'External CT L3 Power',
    address: 618,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_total_power',
    name: 'External CT Total Power',
    address: 619,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_l1_current',
    name: 'External CT L1 Current',
    address: 613,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_l2_current',
    name: 'External CT L2 Current',
    address: 614,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'external_ct_l3_current',
    name: 'External CT L3 Current',
    address: 615,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },

  // --- Grid power (per-phase) ---
  {
    id: 'grid_l1_power',
    name: 'Grid L1 Power',
    address: 622,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'grid_l2_power',
    name: 'Grid L2 Power',
    address: 623,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'grid_l3_power',
    name: 'Grid L3 Power',
    address: 624,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'grid_total_power',
    name: 'Grid Total Power',
    address: 625,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'grid_power_factor',
    name: 'Grid Power Factor',
    address: 621,
    size: 1,
    factor: 0.1,
    unit: '%',
    signed: false,
    deviceClass: 'power_factor',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Inverter output
  // =========================================================================
  {
    id: 'output_voltage_l1',
    name: 'Output Voltage L1',
    address: 627,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'output_voltage_l2',
    name: 'Output Voltage L2',
    address: 628,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'output_voltage_l3',
    name: 'Output Voltage L3',
    address: 629,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'output_current_l1',
    name: 'Output Current L1',
    address: 630,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'output_current_l2',
    name: 'Output Current L2',
    address: 631,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'output_current_l3',
    name: 'Output Current L3',
    address: 632,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_l1_power',
    name: 'Inverter L1 Power',
    address: 633,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_l2_power',
    name: 'Inverter L2 Power',
    address: 634,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_l3_power',
    name: 'Inverter L3 Power',
    address: 635,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'inverter_total_power',
    name: 'Inverter Total Power',
    address: 636,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'output_frequency',
    name: 'Output Frequency',
    address: 638,
    size: 1,
    factor: 0.01,
    unit: 'Hz',
    signed: false,
    deviceClass: 'frequency',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Load
  // =========================================================================
  {
    id: 'load_voltage_l1',
    name: 'Load Voltage L1',
    address: 644,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'load_voltage_l2',
    name: 'Load Voltage L2',
    address: 645,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'load_voltage_l3',
    name: 'Load Voltage L3',
    address: 646,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'load_l1_power',
    name: 'Load L1 Power',
    address: 650,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'load_l2_power',
    name: 'Load L2 Power',
    address: 651,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'load_l3_power',
    name: 'Load L3 Power',
    address: 652,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'load_total_power',
    name: 'Load Total Power',
    address: 653,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'load_frequency',
    name: 'Load Frequency',
    address: 655,
    size: 1,
    factor: 0.01,
    unit: 'Hz',
    signed: false,
    deviceClass: 'frequency',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Battery
  // =========================================================================
  {
    id: 'battery_temperature',
    name: 'Battery Temperature',
    address: 586,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },
  {
    id: 'battery_voltage',
    name: 'Battery Voltage',
    address: 587,
    size: 1,
    factor: 0.01,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'battery_soc',
    name: 'Battery SOC',
    address: 588,
    size: 1,
    factor: 1,
    unit: '%',
    signed: false,
    deviceClass: 'battery',
    stateClass: 'measurement',
  },
  {
    id: 'battery_power',
    name: 'Battery Power',
    address: 590,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'battery_current',
    name: 'Battery Current',
    address: 591,
    size: 1,
    factor: 0.01,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'battery_capacity',
    name: 'Battery Corrected Capacity',
    address: 592,
    size: 1,
    factor: 1,
    unit: 'Ah',
    signed: false,
    stateClass: 'measurement',
  },

  // =========================================================================
  // BMS
  // =========================================================================
  {
    id: 'bms_charging_voltage',
    name: 'BMS Charging Voltage',
    address: 210,
    size: 1,
    factor: 0.01,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'bms_discharging_voltage',
    name: 'BMS Discharging Voltage',
    address: 211,
    size: 1,
    factor: 0.01,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'bms_charging_current_limit',
    name: 'BMS Charging Current Limit',
    address: 212,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'bms_discharging_current_limit',
    name: 'BMS Discharging Current Limit',
    address: 213,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'bms_soc',
    name: 'BMS SOC',
    address: 214,
    size: 1,
    factor: 1,
    unit: '%',
    signed: false,
    deviceClass: 'battery',
    stateClass: 'measurement',
  },
  {
    id: 'bms_voltage',
    name: 'BMS Voltage',
    address: 215,
    size: 1,
    factor: 0.01,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'bms_current',
    name: 'BMS Current',
    address: 216,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: true,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'bms_battery_alarm',
    name: 'BMS Battery Alarm',
    address: 220,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
  },
  {
    id: 'bms_battery_fault',
    name: 'BMS Battery Fault',
    address: 221,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
  },

  // =========================================================================
  // Temperatures
  // =========================================================================
  {
    id: 'dc_temperature',
    name: 'DC Temperature',
    address: 540,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },
  {
    id: 'ac_temperature',
    name: 'AC Temperature',
    address: 541,
    size: 1,
    factor: 0.1,
    unit: '°C',
    signed: false,
    offset: 1000,
    deviceClass: 'temperature',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Generator
  // =========================================================================
  {
    id: 'generator_voltage_l1',
    name: 'Generator Voltage L1',
    address: 661,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'generator_voltage_l2',
    name: 'Generator Voltage L2',
    address: 662,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'generator_voltage_l3',
    name: 'Generator Voltage L3',
    address: 663,
    size: 1,
    factor: 0.1,
    unit: 'V',
    signed: false,
    deviceClass: 'voltage',
    stateClass: 'measurement',
  },
  {
    id: 'generator_l1_power',
    name: 'Generator L1 Power',
    address: 664,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'generator_l2_power',
    name: 'Generator L2 Power',
    address: 665,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'generator_l3_power',
    name: 'Generator L3 Power',
    address: 666,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'generator_total_power',
    name: 'Generator Total Power',
    address: 667,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: true,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Energy totals (daily)
  // =========================================================================
  {
    id: 'day_battery_charge',
    name: 'Day Battery Charge',
    address: 514,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_battery_discharge',
    name: 'Day Battery Discharge',
    address: 515,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_grid_import',
    name: 'Day Grid Import',
    address: 520,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_grid_export',
    name: 'Day Grid Export',
    address: 521,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_load_energy',
    name: 'Day Load Energy',
    address: 526,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_pv_energy',
    name: 'Day PV Energy',
    address: 529,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'day_generator_energy',
    name: 'Day Generator Energy',
    address: 536,
    size: 1,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },

  // =========================================================================
  // Energy totals (lifetime, 32-bit)
  // =========================================================================
  {
    id: 'total_battery_charge',
    name: 'Total Battery Charge',
    address: 516,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_battery_discharge',
    name: 'Total Battery Discharge',
    address: 518,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_grid_import',
    name: 'Total Grid Import',
    address: 522,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_grid_export',
    name: 'Total Grid Export',
    address: 524,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_load_energy',
    name: 'Total Load Energy',
    address: 527,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_pv_energy',
    name: 'Total PV Energy',
    address: 534,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },
  {
    id: 'total_generator_energy',
    name: 'Total Generator Energy',
    address: 537,
    size: 2,
    factor: 0.1,
    unit: 'kWh',
    signed: false,
    deviceClass: 'energy',
    stateClass: 'total_increasing',
  },

  // =========================================================================
  // Hybrid settings (read-only monitoring)
  // =========================================================================
  {
    id: 'work_mode',
    name: 'Work Mode',
    address: 142,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Export First',
      1: 'Zero Export to Load',
      2: 'Zero Export to CT',
    },
  },
  {
    id: 'energy_pattern',
    name: 'Energy Pattern',
    address: 141,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Battery First',
      1: 'Load First',
    },
  },
  {
    id: 'grid_charge_enabled',
    name: 'Grid Charge Enabled',
    address: 130,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Off',
      1: 'On',
    },
  },
  {
    id: 'solar_sell_enabled',
    name: 'Solar Sell Enabled',
    address: 145,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Off',
      1: 'On',
    },
  },
  {
    id: 'battery_shutdown_soc',
    name: 'Battery Shutdown SOC',
    address: 115,
    size: 1,
    factor: 1,
    unit: '%',
    signed: false,
    stateClass: 'measurement',
  },
  {
    id: 'battery_low_soc',
    name: 'Battery Low SOC',
    address: 117,
    size: 1,
    factor: 1,
    unit: '%',
    signed: false,
    stateClass: 'measurement',
  },
  {
    id: 'battery_max_charge_current',
    name: 'Battery Max Charge Current',
    address: 108,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'battery_max_discharge_current',
    name: 'Battery Max Discharge Current',
    address: 109,
    size: 1,
    factor: 1,
    unit: 'A',
    signed: false,
    deviceClass: 'current',
    stateClass: 'measurement',
  },
  {
    id: 'zero_export_power',
    name: 'Zero Export Power',
    address: 104,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },
  {
    id: 'max_sell_power',
    name: 'Max Sell Power',
    address: 143,
    size: 1,
    factor: 1,
    unit: 'W',
    signed: false,
    deviceClass: 'power',
    stateClass: 'measurement',
  },

  // =========================================================================
  // Status & alarms
  // =========================================================================
  {
    id: 'running_status',
    name: 'Running Status',
    address: 500,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
    enumMap: {
      0: 'Standby',
      1: 'Self Check',
      2: 'Normal',
      3: 'Alarm',
      4: 'Fault',
    },
  },
  {
    id: 'ac_relay_status',
    name: 'AC Relay Status',
    address: 552,
    size: 1,
    factor: 1,
    unit: '',
    signed: false,
  },
];
